[global]
    keyboard = "en-us"
    country = "us"
    fqdn = "{{FQDN}}"
    mailto = "{{EMAIL}}"
    timezone = "{{TIMEZONE}}"
    root_password = "{{ROOT_PASSWORD}}"
    reboot_on_error = false

[network]
    source = "from-dhcp"

[disk-setup]
    filesystem = "zfs"
    zfs.raid = "{{ZFS_RAID}}"
    disk_list = {{DISK_LIST}}
